version: '3'

services:
  api:
    build: .
    image: ml_read_card
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 80:8000

  # nginx:
  #   build: ./nginx
  #   image: nginx:1.19-alpine
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
